-- DDL code by R Macdougald-Denton
-- 18-04-2024

drop table Department cascade constraints;
drop table Department_Manager cascade constraints;
drop table Supervisor cascade constraints;
drop table Employees cascade constraints;
drop table Dependents cascade constraints;
drop table Locations cascade constraints;
drop table Projects cascade constraints;
drop table ProjectPersonnel cascade constraints;
drop table Customers cascade constraints;
drop table Products cascade constraints;
drop table Orders cascade constraints;
drop table Warehouse cascade constraints;
drop table Inventory cascade constraints;

-- Create Department Table
create table Department (ID number primary key
, Department_Name varchar2 (50) NOT NULL
, Manager_Name varchar2 (100) NOT NULL
, Sale_Department_Employees_Name Varchar(100)
);

-- Create Department_Manager Table
create table Department_Manager (ID number primary key
, DepartmentID number
, StartDate date NOT NULL
, EndDate date
);

-- Add Foreign Key Constraint to Department Manager Table
alter table Department_Manager add constraint fkey_Department foreign key (DepartmentID) references Department(ID);

-- Create Supervisor Table
create table Supervisor (ID number primary key
, Department_ManagerID number
, SupervisorName varchar2(100) NOT NULL
);

-- Add Foreign Key Constraint to Supervior Table
alter table Supervisor add constraint fkey_Department_Manager foreign key (Department_ManagerID) references Department_Manager(ID);

-- Create Employees Table
create table Employees (ID number primary key
, DepartmentID number
, SupervisorID number
, First_Name varchar2 (50)
, Last_Name varchar2 (50) NOT NULL
, National_Insurance_Number varchar2 (15) NOT NULL
, Address varchar2 (70) NOT NULL
, Salary number NOT NULL
, DateOfBirth varchar2(50) NOT NULL
, EmailAddress varchar2 (50) NOT NULL
, ContactNumber varchar2(50) NOT NULL
, Start_Date date NOT NULL
, Leave_Date date
);

-- Add Foreign Key Constraints to Employees Table
alter table Employees add (constraint fkey_Departments foreign key (DepartmentID) references Department(ID)
, constraint fkey_Supervisor foreign key (SupervisorID) references Supervisor(ID)
);

-- Create Dependents Table
create table Dependents (ID number primary key
, EmployeesID number
, First_Name varchar2 (50) NOT NULL
, Date_of_Birth date NOT NULL
, Relationship varchar2 (50) NOT NULL
);

-- Add Foreign Key Constraints To Dependents Table
alter table Dependents add constraint fkey_Employees foreign key (EmployeesID) references Employees(ID);

-- Create Locations Table
create table Locations (ID number primary key
, DepartmentID number 
, LocationName varchar2 (30) NOT NULL
);

-- Add Foreign Key Constraint to Locations Table
alter table Locations add constraint fkey_Department1 foreign key (DepartmentID) references Department(ID);

-- Create Projects Table
create table Projects (ID number primary key
, DepartmentID number 
, LocationID number
, ProjectName varchar2 (20) NOT NULL
);

-- Add Foreign Key Constraints to Projects Table
alter table Projects add (constraint fkey_Departments1 foreign key (DepartmentID) references Department(ID)
, constraint fkey_Location foreign key (LocationID) references Locations(ID)
);

-- Create Project Personnel Table
create table ProjectPersonnel (ID number primary key
, EmployeesID number
, ProjectsID number 
, Hours_Worked number NOT NULL
, Date_ date
);

-- Add Foreign Key Constraints to Project Personnal Table
alter table ProjectPersonnel add (constraint fkey_Employees1 foreign key (EmployeesID) references Employees(ID)
, constraint fkey_Projects foreign key (ProjectsID) references Projects(ID)
);

-- Create Customers Table
create table Customers (ID number primary key
, DepartmentID number
, First_Name varchar2 (50)
, Last_Name varchar2 (50) NOT NULL
, Email_Address varchar2 (100) NOT NULL
, Contact_Number varchar2(50) NOT NULL
);

-- Add Foreign Key Constraint to Customers Table
alter table Customers add constraint fkey_Department2 foreign key (DepartmentID) references Department(ID);

-- Create Products Table
create table Products (ID number primary key
, ProductName varchar2 (1000)
, Price number (12, 2) NOT NULL
);

-- Create Orders Table
create table Orders (ID number primary key
, CustomersID number 
, ProductsID number 
, Reference_Number varchar2 (100)
, Order_Date date
);

-- Add Foreign Key Constraints to Orders Table
alter table Orders add (constraint fkey_Customers foreign key (CustomersID) references Customers(ID)
, constraint fkey_Products foreign key (ProductsID) references Products(ID)
);

-- Create Warehouse Table
create table Warehouse (ID number primary key
, Warehouse_Name varchar2 (50) NOT NULL
, Located varchar2 (50)
);

-- Create Inventory Table
create table Inventory (ID number generated by default on NULL as identity start with 1000 primary key
, ProductsID number
, WarehouseID number
, Product_Quantity number NOT NULL
);

-- Add Foreign Key Constraints to Inventory Table
alter table Inventory add (constraint fkey_Product foreign key (ProductsID) references Products(ID)
, constraint fkey_Warehouse foreign key (WarehouseID) references Warehouse(ID)
);